-- DEFINE O BANCO DE DADOS SENAI_WISHLIST_DESAFIO SERÁ UTILIZADO
USE SENAI_WISHLIST_DESAFIO;

-- LISTA TODOS OS TIPOS DE USUÁRIOS
SELECT * FROM TiposUsuarios;

-- LISTA TODOS OS USUÁRIOS
SELECT * FROM Usuarios;

-- LISTA TODOS OS DESEJOS
SELECT * FROM Desejos;

-- LISTA OS DESEJOS RELACIONANDO COM O USUÁRIO
SELECT D.Descricao AS Desejo, U.Nome AS Usuario
FROM Desejos D
INNER JOIN Usuarios U
ON
D.UsuarioId = U.Id;