-- CRIA O BANCO DE DADOS SENAI_WISHLIST_DESAFIO
CREATE DATABASE SENAI_WISHLIST_DESAFIO;

-- DEFINE O BANCO DE DADOS SENAI_WISHLIST_DESAFIO SERÁ UTILIZADO
USE SENAI_WISHLIST_DESAFIO;

-- CRIA A TABELA TiposUsuarios COM AS COLUNAS Id E Titulo
CREATE TABLE TiposUsuarios(
	Id INT IDENTITY PRIMARY KEY
	,Titulo VARCHAR(250) NOT NULL UNIQUE
);

-- CRIA A TABELA Usuarios COM AS COLUNAS Id, TipoUsuarioId, Nome, Email E Senha
CREATE TABLE Usuarios(
	Id INT IDENTITY PRIMARY KEY
	,TipoUsuarioId INT NOT NULL FOREIGN KEY REFERENCES TiposUsuarios(Id)
	,Nome VARCHAR(250) NOT NULL UNIQUE
	,Email VARCHAR(250) NOT NULL UNIQUE
	,Senha VARCHAR(250) NOT NULL
);

-- CRIA A TABELA Desejos COM AS COLUNAS Id, Descricao E UsuarioId
CREATE TABLE Desejos(
	Id INT IDENTITY PRIMARY KEY
	,Descricao VARCHAR(250) NOT NULL
	,UsuarioId INT NOT NULL FOREIGN KEY REFERENCES Usuarios(Id)
);